from fastapi import APIRouter
from fastapi import Depends
from fastapi import HTTPException

from sqlalchemy.orm import Session

from backend.schemas.email_schema import EmailSchema
from backend.services.sentiment_service import (
    calculate_sentiment
)
from backend.database.dependencies import get_db

from backend.database.crud import (
    get_email_by_message_id,
    get_thread,
    create_thread,
    save_email,
    get_contact_by_email,
    create_contact,
    create_audit_log
)
from agent.graph import graph
from backend.database.crud import (
    create_action
)
from backend.services.classification_service import classify_email
from backend.services.thread_service import (
    get_thread_history
)
router = APIRouter()

#Endpoint
@router.post("/api/ingest")
def ingest_email(
    email: EmailSchema,
    db: Session = Depends(get_db)
):

    existing = get_email_by_message_id(
        db,
        email.message_id
    )

    if existing:

        raise HTTPException(
            status_code=409,
            detail="Duplicate message_id"
        )

    contact = get_contact_by_email(
        db,
        email.sender
    )

    if not contact:

        contact = create_contact(
            db,
            email.sender
        )

    thread = get_thread(
        db,
        email.thread_id
    )

    if not thread:

        create_thread(
            db,
            email.thread_id,
            email.sender,
            email.subject
        )

    sentiment = calculate_sentiment(
        email.body
    )

    category = classify_email(
        email.body
    )

    stored_email = save_email(
        db,
        email,
        sentiment,
        category
    )

    thread_emails = get_thread_history(
        db,
        email.thread_id
    )

    thread_history = "\n".join(
        e.body
        for e in thread_emails
    )
    print("GRAPH START")
    result = graph.invoke({

        "email": email.body,

        "sender": email.sender,

        "thread_id": email.thread_id,

        "thread_history": thread_history,

        "rag_context": "",

        "category": category,

        "sentiment": sentiment,

        "urgency": "",

        "requires_human": False,

        "reply": "",

        "action_taken": ""
    })
    print("GRAPH DONE")
    create_action(

        db=db,

        email_id=stored_email.id,

        action_type=result["action_taken"],

        content=result["reply"],

        reasoning="Generated by LangGraph"
    )
    print("ACTION SAVED")
    create_audit_log(

        db=db,

        entity_type="email",

        entity_id=stored_email.id,

        action=result["action_taken"]
    )
    print("AUDIT SAVED")

    return {
        "success": True,
        "email_id": stored_email.id,
        "message": "Email Ingested"
    }